### ISSUE TITLE
make it clear that GradPose is a structure superimposition software not a structural alignement software

### ISSUE THREAD

**Issue by LilySnow** [X-lab-3D/GradPose#10]
please make it clear that GradPose is a structure superimposition software not a structural alignement software. Therefore, it should be clear to the users that they have to provide pdb files with exactly the same numbering. To prepare the pdb files so that they have the same numbering, maybe you could refer to Farzaneh's code.

Also make it clear that when pdb files have different number of amino acids, what will happen.

**Comment by KevinVG207** [comment]
@LilySnow I have added the section "PDB requirements" to the README on the [development branch](https://github.com/X-lab-3D/GradPose/tree/development#pdb-requirements). Let me know if that is what you wanted.
